blank_issues_enabled: true
contact_links:
  - name: 💬 Discusiones Generales
    url: https://github.com/Mabci/remuxeador/discussions
    about: Para preguntas, ideas y discusiones generales
  - name: 📚 Documentación
    url: https://github.com/Mabci/remuxeador/blob/main/README.md
    about: Lee la documentación completa del proyecto
